name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 */6 * * *' # 10시간마다 실행
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Keep Alive Commit
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'action@github.com'
        git commit --allow-empty -m "Keep Streamlit Awake"
        git push
